### ISSUE TITLE
Upstream.to showing error-message with activated plugin

### ISSUE THREAD

**Issue by muelleel** [ByteDream/stream-bypass#1]
Cannot use the plugin on upstream.to, the streaming works fine when disabled.

**Comment by ByteDream** [comment]
It seems like they've changed their api so only requests outgoing from the real upstream.to website can request the video file. If the request is made from the addon, all it receives is a 403 error.
The support for the site is dropped until I find a workaround

**Comment by ByteDream** [comment]
Should be fixed in [v2](https://github.com/ByteDream/stream-bypass/releases/tag/v2.0.0)
