### ISSUE TITLE
mp4upload final url uses www4. but some embed sourfe requires www14

### ISSUE THREAD

**Issue by tathastu871** [ByteDream/stream-bypass#10]
https://www14.mp4upload.com:282/d/qwx2hqpdz3b4quuor6qaqoqxcmpxvjg24jimyi3bvte25akjslogcthk/video.mp4

this is url i got latest 
but still it isnt streaming tried on vlc or mpv but unable to stream also tried in browser but failed

**Comment by tathastu871** [comment]
The web page at https://www14.mp4upload.com:282/d/qwx2hqpdz3b4quuor6qaqoqxcmpxvjg24jimyi3bvte25akjsjyqogxs/video.mp4' might be temporarily down or it may have moved permanently to a new web address.

obtained using devtools

**Comment by ByteDream** [comment]
Probably fixed in #12.
