### ISSUE TITLE
chrome 118 UI issue

### ISSUE THREAD

**Issue by Bug-Cache** [ByteDream/stream-bypass#17]
![image](https://github.com/ByteDream/stream-bypass/assets/98657967/d1e67b8c-df0e-49fe-b71c-ff68df6f50ce)

**Comment by ByteDream** [comment]
Fixed in [v3.0.0](https://github.com/ByteDream/stream-bypass/releases/tag/v3.0.0). There are two zipfiles now, if you don't know which to use, check out the [installation section](https://github.com/ByteDream/stream-bypass/tree/v3.0.0#manual-installation).
