### ISSUE TITLE
Add vidstream.pro mcloud.to and filemoon.sx

### ISSUE THREAD

**Issue by NotPhantomX** [ByteDream/stream-bypass#5]

**Comment by ByteDream** [comment]
filemoon is implemented, I'll release the new version with support for it later today or tomorrow.
vidstream and mcloud probably will be supported too, even though the implementation for this sites will be a little dirty

**Comment by ByteDream** [comment]
Vidstream and mcloud isn't possible atm. The way I thought I could implement it does not work / would hit the overall browser performance too hard for just this tiny amount of websites.

**Comment by ByteDream** [comment]
To be a bit clearer: I don't really know how they (vidstream & mcloud) generate their video urls. I assume that their javascript somehow converts the url where the video is embedded in into the url to the actual video. But the javascript is highly obfuscated and I do not have the desire to work me through the huge code mess. The addressed dirty implementation was to interject the whole website traffic and look for a specific request. But if I've implemented this, the code for this action would run on every website for every request which would be unnecessary in 99.9% of the cases.

**Comment by HritikR** [comment]
[animdl](https://github.com/justfoolingaround/animdl) has code for vidstream.pro and mcloud.to 

https://github.com/justfoolingaround/animdl/blob/70ebfd485e2bef7e52ba10819cb92784968dbdc9/animdl/core/codebase/extractors/vidstream/__init__.py#L60-L94
