### ISSUE TITLE
Please add MagellanTV.com

### ISSUE THREAD

**Issue by CHJ85** [ByteDream/stream-bypass#6]
Hi there. MagellanTV uses a redirect script to interrupt the video with their paywall crap after 5 minutes.
So could you please add magellantv.com to your extension? That'd be great.
Thank you.

**Comment by ByteDream** [comment]
This is not in the scope of this project. I mainly focus on sites which are hosting videos without distribute them themself / sites on which a much greater number of different videos are hosted and not just a specific set, like in your request.

**Comment by CHJ85** [comment]
Yea, I know it's not exactly the same. But I thought it'd fit in because the bypass is just a cookie based redirect. And as far as the script name "stream-bypass", it fits right in. 
But please keep it in mind if you ever decide to expend the script's use case.
