### ISSUE TITLE
few provider/domain (`AsianLoad/asianembed`, `StreamSB`, `MultiQuality/gogo-play`) request to add in the extension

### ISSUE THREAD

**Issue by bachig26** [bytedream/stream-bypass#8]
1. AsianLoad (name of the source): https://asianembed.io
- https://github.com/recloudstream/cloudstream/blob/master/app/src/main/java/com/lagradost/cloudstream3/extractors/AsianLoad.kt
- https://github.com/recloudstream/cloudstream/blob/master/app/src/main/java/com/lagradost/cloudstream3/extractors/helper/AsianEmbedHelper.kt

2. StreamSB:
- https://github.com/recloudstream/cloudstream/blob/master/app/src/main/java/com/lagradost/cloudstream3/extractors/StreamSB.kt

3. MultiQuality (name of the source): https://gogo-play.net
- https://github.com/recloudstream/cloudstream/blob/master/app/src/main/java/com/lagradost/cloudstream3/extractors/MultiQuality.kt

@ByteDream I hope to see these above three extractors/domains/providers added to the extension.

I have attached the link below of all the extractors they have in cloudstream, some of them are modified from the aniyomi extension repo where there are more of providers (https://github.com/jmir1/aniyomi-extensions/tree/master/src).
Source of my find: https://github.com/recloudstream/cloudstream/tree/master/app/src/main/java/com/lagradost/cloudstream3/extractors

**Comment by bytedream** [comment]
All sites went down in the meantime :/
